services:
  postgres:
    image: postgres:16-alpine
    container_name: shopping-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopping_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d shopping_db']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shopping-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopping.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5051:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
